### ISSUE TITLE
No output devices

### ISSUE THREAD

**Issue by bbetter** [elementary/switchboard-plug-sound#105]
![image](https://user-images.githubusercontent.com/6604503/51904548-93675e80-23c7-11e9-955e-76fd7eb0f200.png)

sound is working ok, but I can't volume up/down in settings. Works good from external apps,and websites.

**Comment by peteruithoven** [comment]
Could you provide some information on audio hardware? 
What do you see in the Output Devices tab of PulseAudio Volume Control (installable from AppCenter)?

**Comment by bbetter** [comment]
![image](https://user-images.githubusercontent.com/6604503/52051759-21c11900-255d-11e9-9ad7-31f7ece39b6d.png)
something like this in big unscalable window

**Comment by peteruithoven** [comment]
Interesting!
Do you remember changing anything sound settings related?

Could you have a look at whether of any of the solutions offered below are useful?
https://askubuntu.com/questions/976375/kubuntu-17-10-no-audio-devices-found-no-settings-no-sound

Repeat: Could you provide some information on audio hardware?

**Comment by bbetter** [comment]
https://askubuntu.com/a/1006715
This exact answer helps a lot. I think the issue is resolved.
