### ISSUE TITLE
Event sounds vs Event alerts?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/switchboard-plug-sound#107]
In the current Sound settings there is a checkbox for "Event alerts", explained as sound made when the system cannot do something:
![screenshot from 2019-02-07 18-32-05](https://user-images.githubusercontent.com/523210/52430594-c1a31780-2b06-11e9-819b-62d04d003cbb.png)

But this checkbox actually [controls](https://github.com/elementary/switchboard-plug-sound/blob/master/src/OutputPanel.vala#L142) "Event sounds" (org.gnome.desktop.sound.event-sounds), which seem to be something different:
![screenshot from 2019-02-07 18-34-08](https://user-images.githubusercontent.com/523210/52430691-f9aa5a80-2b06-11e9-97dc-04a5004e6822.png)

How should we handle this? There are a couple of issues that assume that this event-sounds settings should be handled differently than is currently explained in the sound settings:
- https://github.com/elementary/switchboard-plug-sound/issues/88
- https://github.com/elementary/files/issues/766

To quote @danrabbit:
> Marking this as "Needs Design" since it's unclear that this is the intended use of that setting.

**Comment by cassidyjames** [comment]
We renamed it to "Event alerts" and added the description, as that's more indicative of what the setting does. If a developer uses `Gdk.beep ()`, this setting determines whether it plays a sound, flashes the screen, or both.

It doesn't control other UI sounds, and I'm not sure we'd want it to. If we did, I think we'd need to add a new setting that all those apps respect.

**Comment by peteruithoven** [comment]
Alright. Thanks for clearing that up.
