### ISSUE TITLE
Default output device is reset on reboot

### ISSUE THREAD

**Issue by jtrees** [elementary/switchboard-plug-sound#109]
#### Steps to Reproduce

1. Boot into elementary OS
1. Open the sound plug
1. Select a different output device
1. Reboot

#### Expected Behaviour

The output device selected in step 3 is still the default output device.

#### Actual Behaviour

The selection from step 3 is ignored. The default output device is once again what it was in step 2.

**Comment by peteruithoven** [comment]
We depend on PulseAudio to store these kind of settings. 

These might be interesting:
https://bbs.archlinux.org/viewtopic.php?id=164868
https://bugs.freedesktop.org/show_bug.cgi?id=73375

`module-switch-on-port-available` is loaded in `/etc/pulse/default.pa`?

**Comment by jtrees** [comment]
Yes.

```
$ cat /etc/pulse/default.pa | grep module-switch-on-port -n
33:load-module module-switch-on-port-available
```

**Comment by jtrees** [comment]
Perhaps I should also mention that I only encounter this issue when I have an external mic plugged in (which is always ^^).

![screenshot from 2019-02-24 19-38-17](https://user-images.githubusercontent.com/5802758/53303549-d6540f00-386b-11e9-9505-29970dcf5a6f.png)

**Comment by peteruithoven** [comment]
So which device would you like to have as default? And through what kind of cable is that connected to your machine? 
What device does it instead default after reboot? And how is that device connected?

**Comment by jtrees** [comment]
I want the Built-In Audio thing to be default (connected via an audio jack to the motherboard). The mic is plugged in via USB and every time I boot with the mic plugged in, that grabs the default selection, regardless of what I selected before rebooting.

**Comment by peteruithoven** [comment]
Yeah I'd raise those issues with the Pulse Audio community, after researching solutions.

**Comment by jtrees** [comment]
Ok. Well thanks for taking the time to point me in the right direction.

**Comment by jtrees** [comment]
I reported an issue here: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/issues/670

**Comment by jtrees** [comment]
Turns out this is what causes the issue:

```
$ cat /etc/pulse/default.pa | grep module-switch-on-connect -n
36:.ifexists module-switch-on-connect.so
37:load-module module-switch-on-connect
```

I'm not sure what your reasons are for including those lines (apparently it is non-default), but removing them solves the issue for me.

**Comment by peteruithoven** [comment]
Well it enables what it says, it connects to devices when they connect which I find really nice. I think I manually enabled this on older versions of elementary OS.
I can't find `module-switch-on-connect` in the elementary OS repo's, so this is probably a Ubuntu customization which we inherit? 
If you'd like to change this I'd suggest opening an issue at: https://github.com/elementary/default-settings/
