### ISSUE TITLE
XPS 17 9700 audio input and output devices not detected

### ISSUE THREAD

**Issue by ibnesayeed** [elementary/switchboard-plug-sound#181]
## What Happened

Using daily builds (which I built on January 16, 2021) I booted into the demo session and found out the the audio does not work.

## Expected Behavior

Both audio input and output should work.

## Steps to Reproduce

1. Boot a Dell XPS 17 (9700 model) into the daily build iso file of elementary OS 6
2. Open sound settings
3. Check both Output and Input tabs, likely showing "No Output Device" message

## Platform Information

* elementary OS 6 Early Access (Linux 5.4.0-62-generic)
* Latest release as of January 16, 2021
* Dell XPS 17 (9700 model)

**Comment by davidmhewitt** [comment]
Could you check if it works on Ubuntu 20.04?

**Comment by ibnesayeed** [comment]
I will give Ubuntu 20.04 a try. However, it is not likely to work either as per [this conversation](https://askubuntu.com/questions/1270442/no-sound-on-xps-17-9700). I don't think that the driver was back-ported to 5.4.x kernel verision, but it looks like they do have it in 5.6+ versions. Unfortunately, Ubuntu 20.04 ships with 5.4, consequently, elementary OS 6 will continue to fail to support new XPS laptops for years to come, unless a new kernel version is shipped in elementary.

**Comment by ibnesayeed** [comment]
Also, [the link](http://xps17.ddns.net/sof-soundwire.zip) in the third step of the [potential solution](https://askubuntu.com/questions/1270442/no-sound-on-xps-17-9700) is broken now.

**Comment by ibnesayeed** [comment]
@davidmhewitt I tried running Ubuntu 20.04 live and did not get the audio devices to work. According to [this article](https://blog.fts.scot/2020/07/04/dell-xps-2020-how-to-get-audio-working-on-linux/), the drivers are added to the Linux kernel version 5.10 and work with Pulseaudio 14. The article also suggest that using the OEM build (i.e., `apt install linux-oem-20.04`) should do the trick if one wants to stay with Ubuntu 20.04. I did not try that yet, because I felt it will require a reboot, which will not persist in case of live booting. If I could build a fresh iso with the OEM kernel, I can try that, but I do not know (yet) what are the steps needed to make that change. Is there something I can change in `elementary/os` repo and build to get an Early Access with the OEM kernel?

**Comment by davidmhewitt** [comment]
Sure, try changing generic to oem here:

https://github.com/elementary/os/blob/c4a51e327b12f93b3033478ce88589496fd7026a/etc/auto/config#L12

**Comment by ibnesayeed** [comment]
Awesome, thanks! Building it now.

```
/tmp$ git clone https://github.com/elementary/os.git

/tmp$ cd os

/tmp/os (master)$ git checkout -b oem
Switched to a new branch 'oem'

/tmp/os (oem)$ sed -i 's/"generic"/"oem"/' etc/auto/config

/tmp/os (oem)$ git diff
diff --git a/etc/auto/config b/etc/auto/config
index 0e28f16..45861a7 100755
--- a/etc/auto/config
+++ b/etc/auto/config
@@ -9,7 +9,7 @@ if [ "$HWE" = "yes" ]; then
     KERNEL_FLAVORS="generic-hwe-${BASEVERSION}"
     XORG_HWE="xserver-xorg-hwe-${BASEVERSION}"
 else
-    KERNEL_FLAVORS="generic"
+    KERNEL_FLAVORS="oem"
 fi
 
 lb config noauto \

/tmp/os (oem)$ docker container run --privileged -i -v /proc:/proc -v $PWD:/working_dir -w /working_dir debian:latest /bin/bash -s etc/terraform-daily-6.0-azure.conf < build.sh > build-stdout.log 2> build-stderr.log &
```

**Comment by ibnesayeed** [comment]
One issue that I will still have is the [inability to enable WiFi when running the newly built ISO in demo mode](https://github.com/elementary/installer/issues/468). Is there a place I can supply a custom password to the default `elementary` user in the config file before building the ISO that I can use when prompted for password? Or the give `sudo` access to the random guest user of the demo mode with `NOPASSWD`. Without that, I will not be able to install any packages unless I choose to install the OS instead of trying it live.

**Comment by davidmhewitt** [comment]
Apologies, I was wrong with my information there. Since `20.04`, you have to add the version too.

So it should be, change `generic` to `oem-20.04`.

The password issue is still one I need to think about. You can temporarily solve the issue by doing the following:

Switch to a tty session (CTRL+ALT+F2) and log in using the user 'elementary'. It shouldn't require a password to login. Then type `passwd` to create a temporary password for the elementary user. Then try switching back to the install/demo session (CTRL+ALT+F7).

**Comment by ibnesayeed** [comment]
Thanks, building the new ISO now. I will let you know how it goes.

Also, thanks for the password trick. :)

**Comment by ibnesayeed** [comment]
I tried setting `KERNEL_FLAVORS` to `oem-20.04` and built the ISO. However, when I booted into it I did not see it reflected. It looks like the build is still including the `generic` kernel.

```
$ uname -a
Linux elementary 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

By the way, I was able to change the password of the user without going to a TTY session. I just used the terminal emulator and ran `su elementary` command, then changed the password and it was good to go.

**Comment by davidmhewitt** [comment]
Did you try searching the build output for `oem` to see if it had tried to install that package?

**Comment by ibnesayeed** [comment]
> Did you try searching the build output for `oem` to see if it had tried to install that package?

I saw this message a moment after I already made a change in the config file to build with `HWE="yes"`, which means my STDOUT and STDERR log files are now being overwritten.

**Comment by davidmhewitt** [comment]
Building with HWE won't work as 20.04 does not have HWE packages yet.

**Comment by ibnesayeed** [comment]
> Building with HWE won't work as 20.04 does not have HWE packages yet.

I figured it out the hard way. ;-)

No, building again without it. Will I be able to check which version of the kernel is installed without booting, but mounting the iso locally and inspecting the file system?

**Comment by davidmhewitt** [comment]
You should be able to see which version was installed in the build logs. Searching for `linux` will probably find the relevant lines.

**Comment by ibnesayeed** [comment]
I see these lines matching `oem`:

```
$ grep -i "oem" build-stdout.log
[2021-01-18 16:49:15] lb config noauto --architectures amd64 --mode ubuntu --initramfs none --distribution focal --parent-distribution focal --archive-areas main restricted universe multiverse --parent-archive-areas main restricted universe multiverse --linux-packages linux-image --linux-flavours oem-20.04 --bootappend-live boot=casper maybe-ubiquity quiet splash --mirror-bootstrap http://azure.archive.ubuntu.com/ubuntu/ --parent-mirror-bootstrap http://azure.archive.ubuntu.com/ubuntu/ --mirror-chroot-security http://security.ubuntu.com/ubuntu/ --parent-mirror-chroot-security http://security.ubuntu.com/ubuntu/ --mirror-binary-security http://security.ubuntu.com/ubuntu/ --parent-mirror-binary-security http://security.ubuntu.com/ubuntu/ --mirror-binary mirror://mirrors.ubuntu.com/mirrors.txt --parent-mirror-binary mirror://mirrors.ubuntu.com/mirrors.txt --keyring-packages ubuntu-keyring --apt-options --yes --option Acquire::Retries=5 --option Acquire::http::Timeout=100 --cache-packages false --cache-stages false --uefi-secure-boot enable --binary-images iso-hybrid --iso-application elementary OS --iso-volume elementary OS --firmware-binary false --firmware-chroot false --zsync false
  linux-base linux-firmware linux-image-5.6.0-1042-oem
  linux-modules-5.6.0-1042-oem linux-sound-base lshw lsof ltrace lvm2 lz4
  bindfs fdutils linux-oem-5.6-tools linux-headers-5.6.0-1042-oem gawk nocache
  linux-base linux-firmware linux-image-5.6.0-1042-oem linux-image-oem-20.04
  linux-modules-5.6.0-1042-oem linux-sound-base lshw lsof ltrace lvm2 lz4
Get:1340 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-modules-5.6.0-1042-oem amd64 5.6.0-1042.46 [53.7 MB]
Get:1341 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-image-5.6.0-1042-oem amd64 5.6.0-1042.46 [9053 kB]
Get:1344 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-image-oem-20.04 amd64 5.6.0.1042.38 [2656 B]
Selecting previously unselected package linux-modules-5.6.0-1042-oem.
Preparing to unpack .../1240-linux-modules-5.6.0-1042-oem_5.6.0-1042.46_amd64.deb ...
Unpacking linux-modules-5.6.0-1042-oem (5.6.0-1042.46) ...
Selecting previously unselected package linux-image-5.6.0-1042-oem.
Preparing to unpack .../1241-linux-image-5.6.0-1042-oem_5.6.0-1042.46_amd64.deb ...
Unpacking linux-image-5.6.0-1042-oem (5.6.0-1042.46) ...
Selecting previously unselected package linux-image-oem-20.04.
Preparing to unpack .../1244-linux-image-oem-20.04_5.6.0.1042.38_amd64.deb ...
Unpacking linux-image-oem-20.04 (5.6.0.1042.38) ...
Setting up linux-modules-5.6.0-1042-oem (5.6.0-1042.46) ...
Setting up linux-image-5.6.0-1042-oem (5.6.0-1042.46) ...
I: /boot/vmlinuz.old is now a symlink to vmlinuz-5.6.0-1042-oem
I: /boot/initrd.img.old is now a symlink to initrd.img-5.6.0-1042-oem
I: /boot/vmlinuz is now a symlink to vmlinuz-5.6.0-1042-oem
I: /boot/initrd.img is now a symlink to initrd.img-5.6.0-1042-oem
Setting up linux-image-oem-20.04 (5.6.0.1042.38) ...
Created symlink /etc/systemd/system/oem-config.service.wants/gpu-manager.service → /lib/systemd/system/gpu-manager.service.
Processing triggers for linux-image-5.6.0-1042-oem (5.6.0-1042.46) ...
update-initramfs: Generating /boot/initrd.img-5.6.0-1042-oem
update-initramfs: Generating /boot/initrd.img-5.6.0-1042-oem
update-initramfs: Generating /boot/initrd.img-5.6.0-1042-oem
update-initramfs: Generating /boot/initrd.img-5.6.0-1042-oem
```

But I see some lines matching `generic`:

```
$ grep -i "generic" build-stdout.log
  linux-headers-5.4.0-62-generic linux-headers-generic linux-libc-dev login
  linux-headers-5.4.0-62-generic linux-headers-generic linux-libc-dev login
Get:213 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-headers-5.4.0-62-generic amd64 5.4.0-62.70 [1233 kB]
Get:214 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-headers-generic amd64 5.4.0.62.65 [2464 B]
```

**Comment by ibnesayeed** [comment]
**SUCCESS!!!**

```
$ uname -r
5.6.0-1042-oem
```

I have verified that built-in mic and speakers are working well, so is the bluetooth one (which was working before as well).

Now, the question is, will the final release have a variation with the OEM kernel or I will have to build it again when it's ready (and how about updates)?

**Comment by davidmhewitt** [comment]
I think it's unlikely that the final release will use the OEM kernel as it's not the kernel that Ubuntu recommends for general use. They say it _should_ be fine, but we're likely to stick with the default. See here for information about the difference between the OEM kernel and the generic:

https://wiki.ubuntu.com/Kernel/OEMKernel

However, it sounds like most things work on your system aside from audio with the generic kernel. So you could install the final release of elementary OS 6.0 when it comes out (with the probably generic kernel), then on the first boot, install the OEM kernel and remove the generic one. You wouldn't need to build a new iso.

You would continue to get updates as normal. Ubuntu updates the OEM kernel as frequently as the generic one I think.

It may be worth you opening an issue in the `os` repository about shipping the OEM kernel however. It then gives a place for other people to request the same and we can get an idea of how much interest there is in iso images with an OEM kernel.

I'm going to close this issue as it's an issue with missing drivers in the kernel, which is outside the scope of this repository.

Thanks for the report!

**Comment by ibnesayeed** [comment]
Thank you so much for all the help. You are awesome! :)
