### ISSUE TITLE
Add module-echo-cancel

### ISSUE THREAD

**Issue by tomaswarynyca** [elementary/switchboard-plug-sound#187]
It would be great to have an option to add the **echo-cancel** module to remove background noise from the microphone.

**Comment by Akryum** [comment]
A toggle to enable noise cancellation no matter the implementation would be very nice in this more remote-work world!

**Comment by Akryum** [comment]
I think a much better implementation would be https://jmvalin.ca/demo/rnnoise/ (GUI => https://github.com/lawl/NoiseTorch)

**Comment by Akryum** [comment]
There is also https://github.com/werman/noise-suppression-for-voice

**Comment by Akryum** [comment]
Also moving to Pipewire would probably be a good idea ^^

**Comment by lenemter** [comment]
Closing as duplicate of https://github.com/elementary/switchboard-plug-sound/issues/26
