### ISSUE TITLE
No Speaker icons when selecting test speakers

### ISSUE THREAD

**Issue by selwynorren** [elementary/switchboard-plug-sound#195]
## What Happened
When testing audio levels I click the button Test Speakers then mini pop up shows with my left and right but there is no speaker icon for the left and right speaker. I just get a grey block with the no entry sign

## Expected Behavior
Speaker I con should show

## Steps to Reproduce
As mentioned above. Could this possibly be as I am making use of a USB Audio Interface and not plugged in using the tradition headphone inputs?

### Logs
No Logs

## Platform Information
Running latest updated Daily Build

I just have to make this side note, On Hera, every time I disable one of the audio input channels and close the system settings, it would always come back on again. in Odin, it works so, so well. Once i disable an Input it remains disabled. Great job guys!!

**Comment by cassidyjames** [comment]
Caused by https://github.com/elementary/icons/pull/1007, should have been avoided by GResourcing the icons but it looks like we missed something.
