### ISSUE TITLE
Input placeholder text seems passive aggressive

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-sound#211]
### What Happened?

When there are no input devices, there is a placeholder that reads:

> ## No Input Device
> There is no input device detected. You might want to add one to start recording anything.

This language is a little stilted and "you might want to" seems kind of passive aggressive imo

### Steps to Reproduce

1. Don't have any input devices attached
2. Open System Settings to the Sound page

### Expected Behavior

This copy should probably be changed to use a more natural tone. Maybe we can find a more relatable phrase than "input devices". I'm not sure if "microphone" is somehow not inclusive enough?

"Recording" also seems too specific as most people probably are using a microphone for chat, but this also seems like an overly obvious consequence of not having a microphone.

It would probably be more helpful to offer advice like "Check that all cables are securely attached and microphones are turned on"

### OS Version

6.x (Odin)

### Software Version

Compiled from git

**Comment by pizzaz93** [comment]
How does the following sound? @danrabbit 
Top placeholder: "No Connected Devices Detected" 
Error description: "Check that all cables are securely attached and devices are powered on"

**Comment by danrabbit** [comment]
@pizzaz93 I think we can be more specific than "devices" because this placeholder is at least specific to the input devices page. So we probably don't want to be more vague than "input"

**Comment by pizzaz93** [comment]
Would prefixing input with audio to read "Audio Input" be a little more specific but still general enough to encompass all potential use cases?

**Comment by danrabbit** [comment]
@pizzaz93 that makes sense to me!

**Comment by pizzaz93** [comment]
@danrabbit I'm new to Elementary should I create a PR to update https://github.com/elementary/switchboard-plug-sound/blob/422565991b2ba447dd943327e43c799fd6e2d62c/src/InputPanel.vala#L88?

**Comment by danrabbit** [comment]
@pizzaz93 yes exactly. Thank you!

**Comment by pizzaz93** [comment]
Created a PR, can I add you to the review, or is the process one of having maintainers review requests on a more rotational basis?

As an aside I grew up in Sacramento and being in a larger city I miss the tight knit developer community I found while living there.

**Comment by danrabbit** [comment]
@pizzaz93 sure you can request my review there! I probably won't follow up until Tuesday since I'm technically out sick right now 😅, but thank you for your branch!

Woo go sactown 🎉
