### ISSUE TITLE
Sliders sometimes set 0 [$25]

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-sound#24]
![screenshot from 2017-04-11 12 10 59](https://cloud.githubusercontent.com/assets/7277719/24926369/3346c6ee-1eb0-11e7-9860-af3e8bdbbc56.png)
![screenshot from 2017-04-11 12 11 33](https://cloud.githubusercontent.com/assets/7277719/24926370/335219ae-1eb0-11e7-94bb-2b387c9611d4.png)

---
There's a bounty on this issue [on Bountysource](https://www.bountysource.com/issues/44035050-sliders-sometimes-don-t-match-actual-volume-at-all)

**Comment by tintou** [comment]
This is an issue with the indicator, open both : 
 * change the volume in the indicator, the volume is changed in the plug
 * change the volume in the plug, the volume isn't changed in the indicator

**Comment by danrabbit** [comment]
This is not an issue with the indicator because the indicator is actually correct about the volume level. The sound plug often reports that the volume is muted when it's not or that the volume is something when it's muted.

**Comment by danrabbit** [comment]
Alright, so now we've got it so that it sets the volume most of the time, but sometimes sets 0
![screenshot from 2017-04-12 09 05 41](https://cloud.githubusercontent.com/assets/7277719/24967625/944ee07a-1f5f-11e7-9110-af4d86e6b8de.png)
