### ISSUE TITLE
Sound settings crashing when entering "Input" submenu

### ISSUE THREAD

**Issue by PawelLawrynowicz** [elementary/switchboard-plug-sound#247]
### What Happened?

After entering sound settings and entering the "Input" submenu the entire window crashes.
I am unable to enter the sound input setting because of that.

### Steps to Reproduce

1. Open "System Settings"
2. Select "Sound"
3. Select "Input"

### Expected Behavior

The window should not crash and I should be able to adjust my sound settings from the "System Settings" window.
The workaround is to use pavucontrol or alsamixer.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

EDIT:
Assertion 'name' failed at ../src/pulse/introspect.c:1647, function pa_context_set_source_mute_by_name(). Aborting.
zsh: IOT instruction  io.elementary.switchboard

### Hardware Info

I'm using ASUS ZenBook 14 UM425Q.
Here is the list of my sound cards and digital audio devices (fetched with arecord -l)
**** List of CAPTURE Hardware Devices ****
card 1: Generic_1 [HD-Audio Generic], device 0: ALC294 Analog [ALC294 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: acp [acp], device 0: DMIC capture dmic-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by lenemter** [comment]
Please launch System Settings from Terminal by typing

```
io.elementary.switchboard
```

Then reproduce the crash and post the terminal output here please.

**Comment by PawelLawrynowicz** [comment]
Sorry for posting an incomplete issue.
Here is the output:
```
Assertion 'name' failed at ../src/pulse/introspect.c:1647, function pa_context_set_source_mute_by_name(). Aborting.
zsh: IOT instruction  io.elementary.switchboard
```

**Comment by lenemter** [comment]
@PawelLawrynowicz I created a branch to fix a crash. Not sure if it works though. Can you test it please? I'll list the instructions below.

1. Open Terminal from Application Menu
2. Type in Terminal `sudo apt install git`
3. `sudo apt build-dep switchboard-plug-sound`
4. `git clone https://github.com/elementary/switchboard-plug-sound.git`
6. `cd switchboard-plug-sound`
7. `git checkout lenemter/try-fix-crash`
8. `meson build --prefix=/usr`
9. `cd build`
10. `sudo ninja install`
11. `io.elementary.switchboard`

This will download required dependencies and install the development version of the plug. Thank you in advance.

**Comment by PawelLawrynowicz** [comment]
@lenemter I followed your instructions and now it doesn't crash anymore.
I also checked if the settings are working correctly and it looks like everything's in order.
Thank you!

**Comment by lenemter** [comment]
@PawelLawrynowicz Thank you for testing this :heart:
