### ISSUE TITLE
After plugging wired headphones, can't switch back to speakers 

### ISSUE THREAD

**Issue by TulparBey** [elementary/switchboard-plug-sound#259]
### What Happened?

After plugging wired headphones, I needed to switch back to speakers (while headphones are still plugged). I tried both desktop panel's sound settings and system settings but it simply ignores my changes and sound is still coming from the headphones.

### Steps to Reproduce

1. While using speakers, plugged in headphones
2. Sound was switched to headphones as it should be
3. Tried to change it back to speakers through desktop panel but didn't work. Sound still came from headphones.
4. Tried changing it via system settings but the result's the same. 

### Expected Behavior

Changing back to speakers should change the main sound device to speakers even if a headphone is connected.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
unfortunately when i try; 'Fails without warning? Get and share debug logs by following'
the result is:

com.github.myteam.myapp: command not found. 

I don't know either it's an app I need to install or sth else but couldn't run it, sorry. However I might do it with a bit of help.
```

### Hardware Info

Asus P8h61 M-LX R1 motherboard
Xeon E3 1230-V2 CPU
16GB DDR3 1600Mhz RAM
RX580 8GB GPU

**Comment by jeremypw** [comment]
This may be a limitation of your soundcard/hardware - it can only handle one device at a time and plugging in the headphones effectively unplugs the internal speakers.  The same happens on my laptop and using e.g. `pavucontrol` gives the same effect - plugging in the headphones makes the speakers unavailable.  So I do not think this is an issue with the plug.

**Comment by jeremypw** [comment]
If you have a Digital Surround soundcard there is probably some clever way of splitting the output to both speakers and headphones but you would need to Google it.

**Comment by TulparBey** [comment]
> This may be a limitation of your soundcard/hardware - it can only handle one device at a time and plugging in the headphones effectively unplugs the internal speakers. The same happens on my laptop and using e.g. `pavucontrol` gives the same effect - plugging in the headphones makes the speakers unavailable. So I do not think this is an issue with the plug.

Thank you for the reply but I don't think that's the case because I can do this without any problems in Windows. I also don't have a separate soundcard if that's what you are talking about. It's the onboard sound chip.

**Comment by jeremypw** [comment]
Not a hardware issue then. Looks like it something to do with the configuration of `alsa` or `pulseaudio` but this complicated. See for example https://forums.linuxmint.com/viewtopic.php?t=325486  I agree it would be nice to have a UI to do this easily.
