### ISSUE TITLE
Clicking "Sounds Settings" in the sound indicator does not open the plug

### ISSUE THREAD

**Issue by matzipan** [elementary/switchboard-plug-sound#33]
This seems to be working fine with other plugs, such as network, bluetooth and notifications, so it's most likely an issue with the plug or the indicator.

**Comment by Philip-Scott** [comment]
It's still connected to the old plug name atm. So it should be changed once the new plug is on daily :)

**Comment by danrabbit** [comment]
Closing since this isn't valid for the sound plug. Nothing can be done in this code base to change which plug the indicator launches

**Comment by danrabbit** [comment]
Wait, I was right the first time: https://github.com/elementary/wingpanel-indicator-sound/blob/master/src/Indicator.vala#L358
