### ISSUE TITLE
Mouse wheel has different behaviour to sound indicator

### ISSUE THREAD

**Issue by artemanufrij** [elementary/switchboard-plug-sound#45]
Reproduce:
1. mouse over sound indicator
2. mouse wheel up -> volume up
3. mouse wheel down -> volume down

open sound settings
1. mouse over volume slider
2. mouse wheel up -> volume **down**
3. mouse wheel down -> volume **up**

**Comment by peteruithoven** [comment]
I think this has been fixed in Juno's new sound settings?
