### ISSUE TITLE
Event sounds doesn't impact volume change sound

### ISSUE THREAD

**Issue by peteruithoven** [elementary/switchboard-plug-sound#88]
Disabling the Event sounds doesn't seem to disable the volume change notification change you get when using the keyboard. Is there another setting we should also change?

It does seem to impact other notification sounds and the sounds the sound indicator makes.

**Comment by megatux** [comment]
Screenshot sound also still present when Event Sounds are disabled.

**Comment by megatux** [comment]
And looks like Files "deletion" complete event, too. See [this other issue in Files](https://github.com/elementary/files/issues/766). I guess it's everywhere.

**Comment by peteruithoven** [comment]
I'm closing this. The intentions of the setting is to control event alerts, see: https://github.com/elementary/switchboard-plug-sound/issues/107#issuecomment-510193956
