### ISSUE TITLE
Expose Screen Reader settings here

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-sound#90]
This is one I could see remaining an "Accessibility" or "Universal Access" feature only, but I'm open to discussion and reporting this here for completeness. Is there a reason not to move it here?

**Comment by danrabbit** [comment]
I'm not sure this is exactly a sound setting so much as it is a feature that happens to use sound. I would be curious to know if users would expect to find this feature in sound settings

**Comment by snowparrot** [comment]
One could argue, it should be in the monitor settings as it is about reading something on the monitor. Do you consider to make it an own app?
